// Generated by jextract

package mpv;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$6 {

    static final FunctionDescriptor mpv_request_log_messages$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_request_log_messages$MH = RuntimeHelper.downcallHandle(
        "mpv_request_log_messages",
        constants$6.mpv_request_log_messages$FUNC
    );
    static final FunctionDescriptor mpv_wait_event$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle mpv_wait_event$MH = RuntimeHelper.downcallHandle(
        "mpv_wait_event",
        constants$6.mpv_wait_event$FUNC
    );
}


