// Generated by jextract

package mpv;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$5 {

    static final FunctionDescriptor mpv_get_property_async$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mpv_get_property_async$MH = RuntimeHelper.downcallHandle(
        "mpv_get_property_async",
        constants$5.mpv_get_property_async$FUNC
    );
    static final FunctionDescriptor mpv_observe_property$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mpv_observe_property$MH = RuntimeHelper.downcallHandle(
        "mpv_observe_property",
        constants$5.mpv_observe_property$FUNC
    );
    static final FunctionDescriptor mpv_unobserve_property$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mpv_unobserve_property$MH = RuntimeHelper.downcallHandle(
        "mpv_unobserve_property",
        constants$5.mpv_unobserve_property$FUNC
    );
    static final FunctionDescriptor mpv_event_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mpv_event_name$MH = RuntimeHelper.downcallHandle(
        "mpv_event_name",
        constants$5.mpv_event_name$FUNC
    );
    static final FunctionDescriptor mpv_event_to_node$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_event_to_node$MH = RuntimeHelper.downcallHandle(
        "mpv_event_to_node",
        constants$5.mpv_event_to_node$FUNC
    );
    static final FunctionDescriptor mpv_request_event$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mpv_request_event$MH = RuntimeHelper.downcallHandle(
        "mpv_request_event",
        constants$5.mpv_request_event$FUNC
    );
}


