// Generated by jextract

package mpv;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$2 {

    static final FunctionDescriptor mpv_set_option$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_set_option$MH = RuntimeHelper.downcallHandle(
        "mpv_set_option",
        constants$2.mpv_set_option$FUNC
    );
    static final FunctionDescriptor mpv_command$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_command$MH = RuntimeHelper.downcallHandle(
        "mpv_command",
        constants$2.mpv_command$FUNC
    );
}


