// Generated by jextract

package mpv;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$0 {

    static final FunctionDescriptor mpv_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle mpv_create$MH = RuntimeHelper.downcallHandle(
        "mpv_create",
        constants$0.mpv_create$FUNC
    );
}


