// Generated by jextract

package mpv;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$3 {

    static final FunctionDescriptor mpv_command_async$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_command_async$MH = RuntimeHelper.downcallHandle(
        "mpv_command_async",
        constants$3.mpv_command_async$FUNC
    );
    static final FunctionDescriptor mpv_set_property$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_set_property$MH = RuntimeHelper.downcallHandle(
        "mpv_set_property",
        constants$3.mpv_set_property$FUNC
    );
}


