// Generated by jextract

package mpv;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$2 {

    static final FunctionDescriptor mpv_get_time_us$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_get_time_us$MH = RuntimeHelper.downcallHandle(
        "mpv_get_time_us",
        constants$2.mpv_get_time_us$FUNC
    );
    static final FunctionDescriptor mpv_free_node_contents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_free_node_contents$MH = RuntimeHelper.downcallHandle(
        "mpv_free_node_contents",
        constants$2.mpv_free_node_contents$FUNC
    );
    static final FunctionDescriptor mpv_set_option$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_set_option$MH = RuntimeHelper.downcallHandle(
        "mpv_set_option",
        constants$2.mpv_set_option$FUNC
    );
    static final FunctionDescriptor mpv_set_option_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_set_option_string$MH = RuntimeHelper.downcallHandle(
        "mpv_set_option_string",
        constants$2.mpv_set_option_string$FUNC
    );
    static final FunctionDescriptor mpv_command$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_command$MH = RuntimeHelper.downcallHandle(
        "mpv_command",
        constants$2.mpv_command$FUNC
    );
    static final FunctionDescriptor mpv_command_node$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mpv_command_node$MH = RuntimeHelper.downcallHandle(
        "mpv_command_node",
        constants$2.mpv_command_node$FUNC
    );
}


