// Generated by jextract

package mpv;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.PathElement;
public class mpv_event_log_message {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("prefix"),
        Constants$root.C_POINTER$LAYOUT.withName("level"),
        Constants$root.C_POINTER$LAYOUT.withName("text"),
        Constants$root.C_INT$LAYOUT.withName("log_level"),
        MemoryLayout.paddingLayout(32)
    ).withName("mpv_event_log_message");
    public static MemoryLayout $LAYOUT() {
        return mpv_event_log_message.$struct$LAYOUT;
    }

    static final VarHandle text$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("text"));

    public static MemoryAddress text$get(MemorySegment seg) {
        return (MemoryAddress)mpv_event_log_message.text$VH.get(seg);
    }

    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


