// Generated by jextract

package mpv;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.PathElement;
public class mpv_event {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("event_id"),
        Constants$root.C_INT$LAYOUT.withName("error"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("reply_userdata"),
        Constants$root.C_POINTER$LAYOUT.withName("data")
    ).withName("mpv_event");
    public static MemoryLayout $LAYOUT() {
        return mpv_event.$struct$LAYOUT;
    }
    static final VarHandle event_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("event_id"));

    public static int event_id$get(MemorySegment seg) {
        return (int)mpv_event.event_id$VH.get(seg);
    }

    static final VarHandle data$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("data"));

    public static MemoryAddress data$get(MemorySegment seg) {
        return (MemoryAddress)mpv_event.data$VH.get(seg);
    }

    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


