// Generated by jextract

package mpv;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.PathElement;
public class mpv_event_property {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("name"),
        Constants$root.C_INT$LAYOUT.withName("format"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("data")
    ).withName("mpv_event_property");
    public static MemoryLayout $LAYOUT() {
        return mpv_event_property.$struct$LAYOUT;
    }
    static final VarHandle name$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("name"));

    public static MemoryAddress name$get(MemorySegment seg) {
        return (MemoryAddress)mpv_event_property.name$VH.get(seg);
    }

    static final VarHandle format$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("format"));

    public static int format$get(MemorySegment seg) {
        return (int)mpv_event_property.format$VH.get(seg);
    }

    static final VarHandle data$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("data"));

    public static MemoryAddress data$get(MemorySegment seg) {
        return (MemoryAddress)mpv_event_property.data$VH.get(seg);
    }

    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


