// Generated by jextract

package mpv;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.PathElement;
public class mpv_event_hook {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("name"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("id")
    ).withName("mpv_event_hook");
    public static MemoryLayout $LAYOUT() {
        return mpv_event_hook.$struct$LAYOUT;
    }
    static final VarHandle name$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("name"));
    public static VarHandle name$VH() {
        return mpv_event_hook.name$VH;
    }
    public static MemoryAddress name$get(MemorySegment seg) {
        return (MemoryAddress)mpv_event_hook.name$VH.get(seg);
    }
    public static void name$set( MemorySegment seg, MemoryAddress x) {
        mpv_event_hook.name$VH.set(seg, x);
    }
    public static MemoryAddress name$get(MemorySegment seg, long index) {
        return (MemoryAddress)mpv_event_hook.name$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void name$set(MemorySegment seg, long index, MemoryAddress x) {
        mpv_event_hook.name$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("id"));
    public static VarHandle id$VH() {
        return mpv_event_hook.id$VH;
    }
    public static long id$get(MemorySegment seg) {
        return (long)mpv_event_hook.id$VH.get(seg);
    }
    public static void id$set( MemorySegment seg, long x) {
        mpv_event_hook.id$VH.set(seg, x);
    }
    public static long id$get(MemorySegment seg, long index) {
        return (long)mpv_event_hook.id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void id$set(MemorySegment seg, long index, long x) {
        mpv_event_hook.id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


