// Generated by jextract

package mpv;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.PathElement;
public class mpv_event_start_file {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("playlist_entry_id")
    ).withName("mpv_event_start_file");
    public static MemoryLayout $LAYOUT() {
        return mpv_event_start_file.$struct$LAYOUT;
    }
    static final VarHandle playlist_entry_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("playlist_entry_id"));
    public static VarHandle playlist_entry_id$VH() {
        return mpv_event_start_file.playlist_entry_id$VH;
    }
    public static long playlist_entry_id$get(MemorySegment seg) {
        return (long)mpv_event_start_file.playlist_entry_id$VH.get(seg);
    }
    public static void playlist_entry_id$set( MemorySegment seg, long x) {
        mpv_event_start_file.playlist_entry_id$VH.set(seg, x);
    }
    public static long playlist_entry_id$get(MemorySegment seg, long index) {
        return (long)mpv_event_start_file.playlist_entry_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void playlist_entry_id$set(MemorySegment seg, long index, long x) {
        mpv_event_start_file.playlist_entry_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


