// Generated by jextract

package locale;

import java.lang.foreign.Addressable;
import java.lang.foreign.MemoryAddress;
import java.lang.invoke.MethodHandle;
public class CLocale  {

    public static MethodHandle setlocale$MH() {
        return RuntimeHelper.requireNonNull(constants$0.setlocale$MH,"setlocale");
    }
    public static MemoryAddress setlocale ( int __category,  Addressable __locale) {
        var mh$ = setlocale$MH();
        try {
            return (MemoryAddress)mh$.invokeExact(__category, __locale);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    public static int LC_NUMERIC() {
        return (int)1L;
    }
}


