// Generated by jextract

package locale;

import java.lang.foreign.MemoryAddress;

class constants$1 {

    static final MemoryAddress NULL$ADDR = MemoryAddress.ofLong(0L);
    static final MemoryAddress LC_GLOBAL_LOCALE$ADDR = MemoryAddress.ofLong(-1L);
}


