// Generated by jextract

package locale;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

class constants$0 {

    static final FunctionDescriptor setlocale$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setlocale$MH = RuntimeHelper.downcallHandle(
        "setlocale",
        constants$0.setlocale$FUNC
    );
}


