// Generated by jextract

package locale;

import static java.lang.foreign.ValueLayout.*;
public class Constants$root {

    static final  OfByte C_CHAR$LAYOUT = JAVA_BYTE;
    static final  OfInt C_INT$LAYOUT = JAVA_INT.withBitAlignment(32);
    static final  OfAddress C_POINTER$LAYOUT = ADDRESS.withBitAlignment(64);
}


